//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeopleIKnow.Resources.Views.Dashboard {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index_de {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index_de() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("PeopleIKnow.Resources.Views.Dashboard.Index_de", typeof(Index_de).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string choose_a_contact_from_the_list {
            get {
                return ResourceManager.GetString("choose a contact from the list", resourceCulture);
            }
        }
        
        internal static string are_you_sure {
            get {
                return ResourceManager.GetString("are you sure", resourceCulture);
            }
        }
        
        internal static string user_deletion_confirmation {
            get {
                return ResourceManager.GetString("user deletion confirmation", resourceCulture);
            }
        }
        
        internal static string successfully_saved {
            get {
                return ResourceManager.GetString("successfully saved", resourceCulture);
            }
        }
        
        internal static string successfully_deleted {
            get {
                return ResourceManager.GetString("successfully deleted", resourceCulture);
            }
        }
        
        internal static string _new {
            get {
                return ResourceManager.GetString("new", resourceCulture);
            }
        }
    }
}
